### PR TITLE
Add wavetables & new pattern format (>=157) support

### PR DESCRIPTION
**Pull request by copyrat90**
This PR adds [wavetables](https://github.com/tildearrow/furnace/blob/master/papers/format.md#wavetable) & [new pattern format (>=157)](https://github.com/tildearrow/furnace/blob/master/papers/format.md#pattern-157) support.

## Other changes

* Fix `read_str(..)` can't parse non-ASCII string
    * It should support UTF-8 [according to the docs](https://github.com/tildearrow/furnace/blob/master/papers/format.md#information)
* Fix Python 3.12 import error
    * Use `field(default_factory=lambda: Enum.VALUE)` instead for some dataclass default values

### CODE REVIEW

**Comment by ZoomTen** [comment]
Seems alright, though I think you should add to `tests/test_furnace.py` (and add some sample modules of the newer format version) to ensure the newer modules are read correctly

**Comment by copyrat90** [comment]
Huh, I found some funky thing in the sample module...

In `skate_or_die` module, the first wavetable's height is `0x1E`->`height=31` (by the way `0x00`->`height=1` ).
So, it should store the values in range `0-30`, but it stores `31` for some reason.

If I open this module up with Furnace, this `31`s are clipped to `30` in the wavetable editor.
but it's not saved to `30` unless I make changes in the editor, or export it as `.fuw` file.

Should I clip the wavetable values to the maximum height when loading?
Or leave it as is?

**Comment by ZoomTen** [comment]
I think you should leave it as-is

**Comment by copyrat90** [comment]
Fixed some bugs while adding tests, I think this should be good now

**Comment by ZoomTen** [comment]
Aight, looks good

**Pull request merged**
